default:
	make -C backend
	make -C frontend

start:
	make -C backend start
	make -C frontend start

stop:
	make -C backend stop
	make -C frontend stop

clean:
	make -C backend clean
	make -C frontend clean

.PHONY: default start stop clean
