Bootstrap: library
From: ubuntu:18.04

%environment
    export LANG=en_US.UTF-8

%post
   apt-get update
   apt-get install -y python3 python3-venv locales

   # Install Flask
   locale-gen en_US.UTF-8
   python3 -m venv /usr/local/flask
   . /usr/local/flask/bin/activate
   pip install Flask flask-cors

%runscript
    cd /srv/www
    export FLASK_APP=qds-backend.py
    . /usr/local/flask/bin/activate
    flask run --host=0.0.0.0

%startscript
    cd /srv/www
    export FLASK_APP=qds-backend.py
    . /usr/local/flask/bin/activate
    flask run --host=0.0.0.0
